/**
 * Emits `m3_fuse.h`: one wasm3 handler per catalog tile, each running the tile's operations back to
 * back with no dispatch between them.
 *
 * wasm3's handlers are written as macro invocations, so each one can be instantiated twice from the
 * same source: once normally, and once with `nextOpPreloaded()` redefined to return, which yields an
 * inlinable step body. A fused handler is those step bodies in sequence. Nothing is rewritten by
 * hand, so the fused semantics are wasm3's own.
 *
 * Tiles are matched against the emitted operation stream after a guest compiles, and the head of each
 * match is overwritten with the fused handler. That is data, not code generation.
 */
import { readFileSync, writeFileSync } from 'node:fs';

const [catalogPath, execPath, outPath] = process.argv.slice(2);
if (!catalogPath || !execPath || !outPath) {
	console.error('usage: gen-fuse.mjs <catalog.json> <m3_exec.h> <out.h>');
	process.exit(2);
}

const fail = (why) => {
	console.error(`gen-fuse: ${why}`);
	process.exit(1);
};

const { handlers, widths } = JSON.parse(readFileSync(catalogPath, 'utf8'));
const src = readFileSync(execPath, 'utf8');

/** which macro invocation defines each handler, so it can be re-instantiated in step mode */
const defs = new Map();
const add = (name, inv) => defs.set(`op_${name}`, inv);
const each = (re, fn) => {
	for (const m of src.matchAll(re)) fn(m[0].trim(), m.slice(1));
};
const args = (s) => s.split(',').map((a) => a.trim());

const BIN = {
	d_m3Op_i: ['_sr', '_rs', '_ss'],
	d_m3OpFunc_i: ['_sr', '_rs', '_ss'],
	d_m3CommutativeOp_i: ['_rs', '_ss'],
	d_m3CommutativeOpFunc_i: ['_rs', '_ss']
};
each(/^\s*(d_m3(?:Commutative)?Op(?:Func)?_i)\s*\(([^)]*)\)/gm, (inv, [fam, a]) => {
	const [t, n] = args(a);
	for (const s of BIN[fam]) add(`${t}_${n}${s}`, inv);
});
each(/^\s*(d_m3Fold(?:Commutative)?Op_i)\s*\(([^)]*)\)/gm, (inv, [fam, a]) => {
	const [t, n] = args(a);
	const sufs = ['_rs_f', '_ss_f'].concat(fam === 'd_m3FoldOp_i' ? ['_sr_f'] : []);
	for (const s of sufs) add(`${t}_${n}${s}`, inv);
});
each(/^\s*d_m3Load_i\s*\(([^)]*)\)/gm, (inv, [a]) => {
	const [d, s] = args(a);
	for (const suf of ['_r', '_s']) add(`${d}_Load_${s}${suf}`, inv);
});
each(/^\s*d_m3LoadFold\s*\(([^)]*)\)/gm, (inv, [a]) => {
	const [, d, s] = args(a);
	for (const suf of ['_r_f', '_s_f']) add(`${d}_Load_${s}${suf}`, inv);
});
each(/^\s*d_m3Store_i\s*\(([^)]*)\)/gm, (inv, [a]) => {
	const [s, d] = args(a);
	for (const suf of ['_rs', '_sr', '_ss']) add(`${s}_Store_${d}${suf}`, inv);
});
each(/^\s*d_m3SetRegisterSetSlot\s*\(([^)]*)\)/gm, (inv, [a]) => {
	const [t] = args(a);
	for (const n of [`SetRegister_${t}`, `SetSlot_${t}`, `PreserveSetSlot_${t}`]) add(n, inv);
});
each(/^\s*d_m3Select_i\s*\(([^)]*)\)/gm, (inv, [a]) => {
	const [t] = args(a);
	for (const suf of ['_rss', '_srs', '_ssr', '_sss']) add(`Select_${t}${suf}`, inv);
});

/** wasm3 writes these out longhand, so there is no invocation to re-run */
const STANDALONE = {
	op_CopySlot_32:
		'd_m3Op(CopySlot_32)\n{\n\tu32* dst = slot_ptr(u32);\n\tu32* src = slot_ptr(u32);\n\t*dst = *src;\n\tnextOpPreloaded();\n}',
	op_CopySlot_64:
		'd_m3Op(CopySlot_64)\n{\n\tu64* dst = slot_ptr(u64);\n\tu64* src = slot_ptr(u64);\n\t*dst = *src;\n\tnextOpPreloaded();\n}',
	op_PreserveCopySlot_32:
		'd_m3Op(PreserveCopySlot_32)\n{\n\tu32* dest = slot_ptr(u32);\n\tu32* src = slot_ptr(u32);\n\tu32* preserve = slot_ptr(u32);\n\t*preserve = *dest;\n\t*dest = *src;\n\tnextOpPreloaded();\n}'
};

const need = [...new Set(handlers.flat())].sort();
const invs = [];
const standalone = [];
for (const n of need) {
	if (!widths[n]) fail(`catalog has no width for ${n}`);
	if (STANDALONE[n]) {
		standalone.push(n);
		continue;
	}
	const inv = defs.get(n);
	if (!inv) fail(`no definition found for ${n}; m3_exec.h may have changed shape`);
	if (!invs.includes(inv)) invs.push(inv);
}

const isTrap = (n) => n.includes('_Load_') || n.includes('_Store_');
const out = [];
const w = (s = '') => out.push(s);

w('/* generated by tools/interp/gen-fuse.mjs - do not edit */');
w('#ifndef m3_fuse_h');
w('#define m3_fuse_h');
w('');
w('M3Result burrow_step_err;');
w('');

// step mode: every handler returns instead of dispatching, so a fused body can call them in turn
w('#undef  d_m3Op');
w('#undef  d_m3PreloadNext');
w('#undef  nextOpPreloaded');
w('#undef  nextOp');
w('#undef  d_outOfBounds');
w('#undef  m3MemCheck');
w('#undef  newTrap');
w(
	'#define d_m3Op(NAME) M3_NO_UBSAN static inline __attribute__((always_inline)) i64 vectorcall step_##NAME (d_m3OpSig)'
);
w('#define d_m3PreloadNext()');
w('#define nextOpPreloaded()        return _r0');
w('#define nextOp()                 return _r0');
w('#define newTrap(err)             { burrow_step_err = (err); return 0; }');
w('#define d_outOfBounds            newTrap (m3Err_trapOutOfBoundsMemoryAccess)');
w('#define m3MemCheck(x)            M3_LIKELY (x)');
w('');
for (const inv of invs) w(inv);
for (const n of standalone) w(STANDALONE[n]);
w('');

w('#undef  d_m3Op');
w('#undef  d_m3PreloadNext');
w('#undef  nextOpPreloaded');
w('#undef  nextOp');
w('#undef  d_outOfBounds');
w('#undef  m3MemCheck');
w('#undef  newTrap');
w('#define d_m3Op(NAME) M3_NO_UBSAN d_m3RetSig op_##NAME (d_m3OpSig)');
w('#define d_m3PreloadNext()');
w('#define nextOpPreloaded()        nextOpDirect()');
w('#define nextOp()                 nextOpDirect()');
w('#define newTrap(err)             return err');
w('#define d_outOfBounds            newTrap (m3Err_trapOutOfBoundsMemoryAccess)');
w('#define m3MemCheck(x)            M3_LIKELY (x)');
w('');

const meta = handlers.map((key) => {
	const ws = key.map((n) => widths[n]);
	const off = key.map((_, j) => ws.slice(0, j).reduce((a, b) => a + b, 0));
	return { key, off, width: ws.reduce((a, b) => a + b, 0), trap: key.some(isTrap) };
});

meta.forEach((m, i) => {
	w(`d_m3Op (burrow_fuse_${i})`);
	w('{');
	m.key.forEach((n, j) => {
		w(`\t_r0 = step_${n.slice(3)} (_pc + ${m.off[j]}, _sp, _mem, _r0, _fp0);`);
	});
	// a trap inside the tile must stop it, or the remaining operations commit after the fault
	if (m.trap) {
		w('\tif (M3_UNLIKELY (burrow_step_err))');
		w('\t{');
		w('\t\tM3Result e = burrow_step_err;');
		w('\t\tburrow_step_err = NULL;');
		w('\t\treturn e;');
		w('\t}');
	}
	w(`\t_pc += ${m.width - 1};`);
	w('\tnextOpDirect ();');
	w('}');
});
w('');

w(`#define BURROW_FUSE_N ${meta.length}`);
meta.forEach((m, i) => {
	const want = m.key.map((n) => `(IM3Operation) op_${n.slice(3)}`).join(', ');
	w(`static const IM3Operation g_want_${i}[${m.key.length}] = { ${want} };`);
	w(`static const u16 g_off_${i}[${m.off.length}] = { ${m.off.join(', ')} };`);
});
w('');
w('typedef struct');
w('{');
w('\tIM3Operation head;');
w('\tconst IM3Operation* want;');
w('\tconst u16* off;');
w('\tu8 n;');
w('\tu16 width;');
w('} BurrowFuse;');
w('');
w(`static const BurrowFuse g_burrow_fuse[BURROW_FUSE_N] =`);
w('{');
meta.forEach((m, i) => {
	w(
		`\t{ (IM3Operation) op_burrow_fuse_${i}, g_want_${i}, g_off_${i}, ${m.key.length}, ${m.width} },`
	);
});
w('};');
w('');
w(readFileSync(new URL('./fuse-runtime.inc', import.meta.url), 'utf8').trimEnd());
w('');
w('#endif');

writeFileSync(outPath, `${out.join('\n')}\n`);
const tiles = meta.length;
const ops = meta.reduce((a, m) => a + m.key.length, 0);
console.log(
	`gen-fuse: ${tiles} fused handlers over ${ops} operations, ${need.length} distinct ops`
);
