import { readFile } from 'node:fs/promises';
import { beforeAll, describe, expect, it } from 'vitest';
import { createInterpreter, type WasmInterpreter } from '../../src/interpret.js';
import { wat } from '../node/wat.js';

/**
 * The workload suite behind the cost law.
 *
 * It asserts PROPERTIES, never magnitudes. An absolute nanosecond figure belongs to `burrow probe`
 * on a deploy, because an in-worker clock reads 0 on the edge and the local-to-edge factor runs 2.2x
 * to 6.1x. What a spec can check is that the instrument is measuring what it claims to.
 *
 * Three instrument bugs were caught while producing the numbers this suite exists to reproduce, each
 * by disbelieving a flat line. They are the three rules below, and each is a correctness check
 * rather than a benchmark:
 *
 *   1. a native arm that does not scale with the work is not doing the work
 *   2. a pointer chase must be a real cycle, not a self-loop on one element
 *   3. every case states whether its iterations are dependent, because that alone moved one
 *      measurement between 20.29x and 9.54x with nothing else changed
 *
 * Registered behind BURROW_BENCH rather than skipped: a lane that did not run must not read like a
 * lane that passed.
 */

const ENABLED = process.env.BURROW_BENCH === '1';

let vm: WasmInterpreter;

beforeAll(async () => {
	if (!ENABLED) return;
	const Module = WebAssembly.Module as unknown as new (bytes: BufferSource) => WebAssembly.Module;
	vm = await createInterpreter({
		module: new Module(
			await readFile(new URL('../../src/vendor/wasm3.wasm', import.meta.url).pathname)
		)
	});
});

/** a chain of `n` dependent multiply-adds, which offers the host no instruction-level parallelism */
const dependent = (body: number) => `(module
  (func (export "run") (param $n i32) (result i32)
    (local $acc i32)
    (local.set $acc (i32.const 1))
    (loop $l
      ${Array.from({ length: body }, () => '(local.set $acc (i32.add (i32.mul (local.get $acc) (i32.const 3)) (i32.const 7)))').join('\n      ')}
      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l (local.get $n)))
    (local.get $acc))
)`;

/** `lanes` independent chains, which lets the host issue them in parallel */
const independent = (lanes: number) => `(module
  (func (export "run") (param $n i32) (result i32)
    ${Array.from({ length: lanes }, (_, i) => `(local $a${i} i32)`).join(' ')}
    ${Array.from({ length: lanes }, (_, i) => `(local.set $a${i} (i32.const ${i + 1}))`).join('\n    ')}
    (loop $l
      ${Array.from({ length: lanes }, (_, i) => `(local.set $a${i} (i32.add (i32.mul (local.get $a${i}) (i32.const 3)) (i32.const 7)))`).join('\n      ')}
      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
      (br_if $l (local.get $n)))
    ${Array.from({ length: lanes }, (_, i) => `(local.get $a${i})`).join(' ')}
    ${Array.from({ length: lanes - 1 }, () => '(i32.add)').join(' ')})
)`;

/** walks a permutation stored in memory; one dependent load per step, so it defeats the prefetcher */
const CHASE = `(module
  (memory (export "memory") 32)
  (func (export "chase") (param $steps i32) (result i32)
    (local $p i32)
    (loop $l
      (local.set $p (i32.load (i32.mul (local.get $p) (i32.const 4))))
      (local.set $steps (i32.sub (local.get $steps) (i32.const 1)))
      (br_if $l (local.get $steps)))
    (local.get $p))
)`;

/** a deterministic PRNG, so a failure is reproducible rather than a story about one run */
function rng(seed: number): () => number {
	let state = seed >>> 0;
	return () => {
		state = (state * 1664525 + 1013904223) >>> 0;
		return state / 0x100000000;
	};
}

/**
 * Sattolo's algorithm: a shuffle of the identity that is guaranteed to be a SINGLE cycle of length
 * n, so following it from 0 touches every slot before returning.
 *
 * A modular stride looks like a permutation and is not one. `(i + 1) * 3 % 1021` reads as a cycle
 * through every slot and actually walks the multiplicative subgroup generated by 3, which here has
 * 34 elements out of 1021 - small enough to sit in L1 and measure nothing.
 */
function sattolo(n: number, seed = 0x5eed): Uint32Array {
	const next = new Uint32Array(n);
	for (let i = 0; i < n; i++) next[i] = i;
	const random = rng(seed);
	for (let i = n - 1; i > 0; i--) {
		const j = Math.floor(random() * i);
		const swap = next[i] as number;
		next[i] = next[j] as number;
		next[j] = swap;
	}
	return next;
}

/** median of five, because a single timing on a laptop is a sample of the scheduler */
function time(run: () => void, reps = 5): number {
	const runs: number[] = [];
	for (let i = 0; i < reps; i++) {
		const start = process.hrtime.bigint();
		run();
		runs.push(Number(process.hrtime.bigint() - start));
	}
	return runs.sort((a, b) => a - b)[Math.floor(reps / 2)] as number;
}

describe.skipIf(!ENABLED)('benchmark rule 1: the native arm must scale with the work', () => {
	it('rejects a loop body the optimiser can fold to a constant', () => {
		// `acc = acc + 3` N times folds to `acc + 3N`, so native reads the same time for a body of 10
		// and a body of 262. Any arm that does not scale is not running the work it claims to
		const fold = (body: number) => {
			let acc = 1;
			for (let i = 0; i < 200_000; i++) for (let j = 0; j < body; j++) acc = acc + 3;
			return acc;
		};
		const small = time(() => fold(4));
		const large = time(() => fold(64));

		// 16x the work must show up as more than 4x the time, or the arm is measuring nothing
		expect(large / small).toBeGreaterThan(4);
	});

	it('holds for the interpreted arm too', async () => {
		// one copy against 64, because the loop's own 5 instructions are a fixed cost the short arm
		// cannot escape: at 2 copies against 32 the expected ratio is only about 5 and sits too close
		// to the bound to survive a noisy reading
		const short = vm.load(wat(dependent(1)));
		const long = vm.load(wat(dependent(64)));

		// wasm3 compiles a function on first call, so an unwarmed arm charges compilation to the
		// first timed rep
		short.call('run', 1000);
		long.call('run', 1000);

		const small = time(() => void short.call('run', 20_000), 7);
		const large = time(() => void long.call('run', 20_000), 7);
		expect(large / small).toBeGreaterThan(4);
	});
});

describe.skipIf(!ENABLED)('benchmark rule 2: a pointer chase must be a real cycle', () => {
	it('rejects a modular stride, which is not a cycle however much it looks like one', () => {
		const slots = 1021;
		const strided = new Uint32Array(slots);
		for (let i = 0; i < slots; i++) strided[i] = ((i + 1) * 3) % slots;

		const walk = (next: Uint32Array) => {
			const seen = new Set<number>();
			let p = 0;
			while (!seen.has(p)) {
				seen.add(p);
				p = next[p] as number;
			}
			return seen.size;
		};

		// the shape of the original bug: it reads as a permutation and walks a tiny subgroup
		expect(walk(strided)).toBeLessThan(slots / 2);
		// Sattolo is a single cycle by construction, so it touches every slot
		expect(walk(sattolo(slots))).toBe(slots);
	});

	it('sends the self-loop case straight back to L1, which is what made it read 0.19 ns', () => {
		// `buf[i] = (i * stride) % n` puts 0 at slot 0, so the chase never moves at all
		const broken = new Uint32Array(1024);
		for (let i = 0; i < 1024; i++) broken[i] = (i * 4) % 1024;
		expect(broken[0]).toBe(0);
	});

	it('costs more per step on a working set that does not fit in cache', async () => {
		const guest = vm.load(wat(CHASE));
		const per = (slots: number) => {
			const next = sattolo(slots);
			guest.write(0, new Uint8Array(next.buffer, next.byteOffset, next.byteLength));
			return time(() => void guest.call('chase', 100_000)) / 100_000;
		};
		// 4 KiB against 2 MiB: the larger set misses on every step, so it costs strictly more
		const small = per(1021);
		const large = per(524_287);
		expect(large).toBeGreaterThan(small);
	});
});

describe.skipIf(!ENABLED)(
	'benchmark rule 3: dependence is a property of the case, and it moves the ratio',
	() => {
		it('costs the interpreter about the same per instruction either way', async () => {
			// the interpreter is flat: its cost is per dispatch and does not care about dependence
			const chain = vm.load(wat(dependent(8)));
			const lanes = vm.load(wat(independent(8)));
			const a = time(() => void chain.call('run', 50_000));
			const b = time(() => void lanes.call('run', 50_000));
			expect(Math.max(a, b) / Math.min(a, b)).toBeLessThan(2.5);
		});

		it('costs the host far less when the iterations are independent', () => {
			const chain = () => {
				let a = 1;
				for (let i = 0; i < 2_000_000; i++) a = (a * 3 + 7) | 0;
				return a;
			};
			const lanes = () => {
				let a = 1,
					b = 2,
					c = 3,
					d = 4;
				for (let i = 0; i < 500_000; i++) {
					a = (a * 3 + 7) | 0;
					b = (b * 3 + 7) | 0;
					c = (c * 3 + 7) | 0;
					d = (d * 3 + 7) | 0;
				}
				return a + b + c + d;
			};
			// the same instruction count, differing only in dependence. The independent form issues in
			// parallel and finishes sooner, so the ratio against an interpreter is at its widest here
			expect(time(lanes)).toBeLessThan(time(chain));
		});
	}
);

describe.skipIf(!ENABLED)('the law holds its shape', () => {
	it('charges a cheap guest instruction more, relative to native, than an expensive one', async () => {
		const op = (instruction: string) => `(module
		  (func (export "run") (param $n i32) (result i32)
		    (local $acc i32)
		    (local.set $acc (i32.const 123456789))
		    (loop $l
		      (local.set $acc ${instruction})
		      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
		      (br_if $l (local.get $n)))
		    (local.get $acc))
		)`;
		const add = vm.load(wat(op('(i32.add (local.get $acc) (i32.const 3))')));
		const rem = vm.load(wat(op('(i32.rem_u (local.get $acc) (i32.const 1000003))')));

		const cheap = time(() => void add.call('run', 300_000));
		const costly = time(() => void rem.call('run', 300_000));

		// dispatch executes in the out-of-order window alongside the guest's own arithmetic, so the
		// costlier guest operation is NOT proportionally costlier interpreted
		expect(costly / cheap).toBeLessThan(5);
	});
});

describe.skipIf(!ENABLED)('the law, as a falsifiable property', () => {
	/** Sattolo over `slots`, written into guest memory as byte offsets */
	function seed(guest: { write: (p: number, d: Uint8Array) => void }, slots: number) {
		const next = sattolo(slots);
		const bytes = new Uint32Array(slots);
		for (let i = 0; i < slots; i++) bytes[i] = (next[i] as number) * 4;
		guest.write(0, new Uint8Array(bytes.buffer));
	}

	const CHASE = `(module (memory (export "m") 512)
	  (func (export "run") (param $n i32) (result i32)
	    (local $p i32)
	    (loop $l
	      (local.set $p (i32.load (i32.mul (local.get $p) (i32.const 4))))
	      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
	      (br_if $l (local.get $n)))
	    (local.get $p)))`;

	it('costs less per load, relative to native, as the working set grows', async () => {
		const bytes = wat(CHASE);
		const Module = WebAssembly.Module as unknown as new (b: BufferSource) => WebAssembly.Module;
		const compiled = new Module(bytes);

		/** the median of several paired ratios, because one cache-sensitive reading is a coin flip */
		const ratioAt = async (slots: number) => {
			const instance = (await WebAssembly.instantiate(compiled, {})) as unknown as {
				exports: { run: (n: number) => number; m: WebAssembly.Memory };
			};
			const next = sattolo(slots);
			new Uint32Array(instance.exports.m.buffer, 0, slots).set(next);
			instance.exports.run(1000);

			const guest = vm.load(bytes);
			guest.write(0, new Uint8Array(next.buffer, next.byteOffset, next.byteLength));
			guest.call('run', 1000);

			const ratios: number[] = [];
			for (let r = 0; r < 5; r++) {
				const native = time(() => void instance.exports.run(100_000), 3);
				const interpreted = time(() => void guest.call('run', 100_000), 3);
				ratios.push(interpreted / native);
			}
			ratios.sort((a, b) => a - b);
			return ratios[2] as number;
		};

		// 16 KiB sits in L1 and 16 MiB does not, so the guest stalls in the second and the
		// interpreter's constant overhead hides behind those stalls
		const small = await ratioAt(4_096);
		const large = await ratioAt(4_194_304);

		// the property, not a magnitude: the same guest costs relatively less the more it stalls,
		// which is the whole content of the law. Absolute figures belong to a deploy, and a laptop's
		// cache hierarchy is not the edge's
		expect(large).toBeLessThan(small);
	});

	it('costs a near-constant amount per guest instruction whatever the guest does', async () => {
		// the whole content of the law: the interpreter is flat and native is what swings. Asserted as
		// a comparison of the two spreads rather than against a fixed bound, so a scheduler hiccup
		// moves both arms and the property still holds
		const shapes = [
			'(i32.add (local.get $acc) (i32.const 3))',
			'(i32.mul (local.get $acc) (i32.const 1103515245))',
			'(i32.rem_u (local.get $acc) (i32.const 1000003))'
		];
		const source = (op: string) => `(module
		  (func (export "run") (param $n i32) (result i32)
		    (local $acc i32)
		    (local.set $acc (i32.const 123456789))
		    (loop $l
		      (local.set $acc ${op})
		      (local.set $n (i32.sub (local.get $n) (i32.const 1)))
		      (br_if $l (local.get $n)))
		    (local.get $acc)))`;

		const Module = WebAssembly.Module as unknown as new (b: BufferSource) => WebAssembly.Module;
		const interpreted: number[] = [];
		const native: number[] = [];

		for (const op of shapes) {
			const bytes = wat(source(op));

			const guest = vm.load(bytes);
			guest.call('run', 1000);
			interpreted.push(time(() => void guest.call('run', 200_000), 7));

			const instance = (await WebAssembly.instantiate(new Module(bytes), {})) as unknown as {
				exports: { run: (n: number) => number };
			};
			instance.exports.run(1000);
			native.push(time(() => void instance.exports.run(200_000), 7));
		}

		const spread = (xs: number[]) => Math.max(...xs) / Math.min(...xs);
		// add, mul and rem cost wildly different amounts natively and nearly the same interpreted
		expect(spread(interpreted)).toBeLessThan(spread(native));
	});
});
